# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         RPC-Oracle
version:      1.3
version_from: lib/RPC/Oracle.pm
installdirs:  site
requires:
    DBD::Oracle:                   
    DBI:                           

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
